=== MOHSUJOD/stereoscope/stereoscope/src/main/java/model/MixerSurfaceDocumentSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.theta-tontechnik.de/stereoscope/MixerSurfaceDocumentSchema" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.theta-tontechnik.de/stereoscope/MixerSurfaceDocumentSchema">

    <element name="MixerSurfaceDocument" type="tns:MixerSurfaceDocumentType"></element>

    <complexType name="MixerSurfaceDocumentType">
    	<sequence>
    		<element name="version" type="int"></element>
    		<element name="MixerName" type="string"></element>
    		<element name="MidiInputPortName" type="string"></element>
    		<element name="MidiOutputPortName" type="string"></element>
    		<element name="Surfaces" type="tns:SurfaceType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="SurfaceType">
        <annotation>
        	<documentation>This represents a TouchOscSurface object in the application.</documentation>
        </annotation>
        <sequence>
    		<element name="Name" type="string"></element>
    		<element name="IpAddress" type="string"></element>
    		<element name="PortIncoming" type="int"></element>
    		<element name="PortOutgoing" type="int"></element>
    		<element name="SnapFaders" type="boolean"></element>
    		<element name="HasStickyAux" type="boolean"></element>
    		<element name="StickyAuxNumber" type="int"></element>
    	</sequence>
    </complexType>


</schema>

=== MOHSUJOD/stereoscope/stereoscope/src/main/java/model/SampleMixerSurfaceDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:MixerSurfaceDocument xmlns:tns="http://www.theta-tontechnik.de/stereoscope/MixerSurfaceDocumentSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.theta-tontechnik.de/stereoscope/MixerSurfaceDocumentSchema MixerSurfaceDocumentSchema.xsd ">
  <tns:version>0</tns:version>
  <tns:MixerName>yamaha-01v96</tns:MixerName>
  <tns:MidiInputPortName>YAMAHA 01v96-1</tns:MidiInputPortName>
  <tns:MidiOutputPortName>YAMAHA 01v96-1</tns:MidiOutputPortName>
  <tns:Surfaces>
    <tns:Name>Tobis iPad</tns:Name>
    <tns:IpAddress>192.168.0.150</tns:IpAddress>
    <tns:PortIncoming>8000</tns:PortIncoming>
    <tns:PortOutgoing>9000</tns:PortOutgoing>
    <tns:SnapFaders>false</tns:SnapFaders>
    <tns:HasStickyAux>true</tns:HasStickyAux>
    <tns:StickyAuxNumber>3</tns:StickyAuxNumber>
  </tns:Surfaces>
</tns:MixerSurfaceDocument>
